/** @type {import('tailwindcss').Config} */
const token = (name) => `rgb(var(${name}) / <alpha-value>)`;

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Sora", "DM Sans", "sans-serif"],
      },
      colors: {
        canvas: token("--color-canvas"),
        "canvas-soft": token("--color-canvas-soft"),
        surface: token("--color-surface"),
        "on-brand": token("--color-on-brand"),
        "surface-soft": token("--color-surface-soft"),
        "surface-muted": token("--color-surface-muted"),
        line: token("--color-line"),
        "line-soft": token("--color-line-soft"),
        "line-strong": token("--color-line-strong"),
        ink: token("--color-text-primary"),
        secondary: token("--color-text-secondary"),
        muted: token("--color-text-muted"),
        subtle: token("--color-text-subtle"),
        brand: token("--color-brand"),
        "brand-soft": token("--color-brand-soft"),
        "brand-muted": token("--color-brand-muted"),
        "brand-border": token("--color-brand-border"),
        "brand-hover": token("--color-brand-hover"),
        "brand-focus": token("--color-brand-focus"),
        "brand-strong": token("--color-brand-strong"),
        "brand-deep": token("--color-brand-deep"),
        "brand-darker": token("--color-brand-darker"),
        "brand-contrast": token("--color-brand-contrast"),
        danger: token("--color-danger"),
        "danger-soft": token("--color-danger-soft"),
        "danger-border": token("--color-danger-border"),
        "danger-strong": token("--color-danger-strong"),
        warning: token("--color-warning"),
        "warning-soft": token("--color-warning-soft"),
        "warning-border": token("--color-warning-border"),
        "warning-strong": token("--color-warning-strong"),
        caution: token("--color-caution"),
        "caution-soft": token("--color-caution-soft"),
        "caution-border": token("--color-caution-border"),
        "caution-strong": token("--color-caution-strong"),
        success: token("--color-success"),
        "success-soft": token("--color-success-soft"),
        "success-border": token("--color-success-border"),
        "success-strong": token("--color-success-strong"),
        info: token("--color-info"),
        "info-soft": token("--color-info-soft"),
        "info-border": token("--color-info-border"),
        "info-strong": token("--color-info-strong"),
        "violet-soft": token("--color-violet-soft"),
        "violet-border": token("--color-violet-border"),
        "violet-strong": token("--color-violet-strong"),
        "stat-teal-soft": token("--color-stat-teal-soft"),
        "stat-teal": token("--color-stat-teal"),
        "stat-orange-soft": token("--color-stat-orange-soft"),
        "stat-orange": token("--color-stat-orange"),
        "stat-violet-soft": token("--color-stat-violet-soft"),
        "stat-violet": token("--color-stat-violet"),
        "stat-blue-soft": token("--color-stat-blue-soft"),
        "stat-blue": token("--color-stat-blue"),
      },
      boxShadow: {
        soft: "0 8px 32px rgba(24,49,47,.07)",
        lift: "0 14px 40px rgba(24,49,47,.12)",
        float: "0 14px 36px rgba(15,23,42,.14)",
      },
      keyframes: {
        "toast-in": {
          from: { opacity: "0", transform: "translateY(-8px) scale(.98)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
      },
      animation: { "toast-in": "toast-in 180ms ease-out" },
      backgroundImage: { "dot-grid": "radial-gradient(#c8d8d4 1px, transparent 1px)" },
    },
  },
  plugins: [],
};
